/* Auto-generated by scripts/export_portfolio.py — do not edit by hand */
window.POLICYSHIFT_CARD = {
  "title": "PolicyShift",
  "subtitle": "When enterprise SOPs version, do tool agents still decide safely? Eval + version-aware RAG + preference data",
  "github": "https://github.com/ishikanahar/policyshift",
  "highlights": [
    {
      "label": "RAG task success",
      "value": "0.75",
      "detail": "vs baseline 0.58"
    },
    {
      "label": "Stale@5 (date-filtered)",
      "value": "0.00",
      "detail": "vs naive 0.45"
    },
    {
      "label": "Preference pairs",
      "value": "120",
      "detail": "current/stale · grounded/unsupported · safe/unsafe"
    },
    {
      "label": "Domains × versions",
      "value": "3 × 3",
      "detail": "120+ cases"
    }
  ],
  "methods": [
    "Version-aware retrieval",
    "Teacher distillation (smoke)",
    "DPO preference pairs (smoke)",
    "Continual replay protocols",
    "TeacherBudget selection",
    "Verifier-guided RL smoke"
  ],
  "disclaimer": "Synthetic benchmark. Smoke students may replay teachers; metrics are from executed artifacts, not invented scores."
};
